### ISSUE TITLE
Compile error on Mint 18.2

### ISSUE THREAD

**Issue by teol** [Douane/Douane#78]
Hello,

I'd like to try Douane so I followed the wiki's steps to install dependencies and compile.
But a problem occurs when I try to compile the douane-dkms kernel module.

Here are a few information:
```
teo@teo-ThinkPad-T570 ~/Documents/douane/douane-dkms $ sudo make dkms
[sudo] password for teo: 
Installing Douane Linux kernel module version 0.8.2...

Creating symlink /var/lib/dkms/douane/0.8.2/source ->
                 /usr/src/douane-0.8.2

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=4.13.0-31-generic -C /lib/modules/4.13.0-31-generic/build M=/var/lib/dkms/douane/0.8.2/build....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.13.0-31-generic (x86_64)
Consult /var/lib/dkms/douane/0.8.2/build/make.log for more information.
Makefile:77: recipe for target 'dkms' failed
make: *** [dkms] Error 10
```

```
teo@teo-ThinkPad-T570 ~/Documents/douane/douane-dkms $ uname -r
4.13.0-31-generic


teo@teo-ThinkPad-T570 ~/Documents/douane/douane-dkms $ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya
```

Build log:
```
DKMS make.log for douane-0.8.2 for kernel 4.13.0-31-generic (x86_64)
Thu Jan 25 11:50:18 CET 2018
make[1]: Entering directory '/usr/src/linux-headers-4.13.0-31-generic'
  AR      /var/lib/dkms/douane/0.8.2/build/built-in.o
  CC [M]  /var/lib/dkms/douane/0.8.2/build/douane.o
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘task_exe_path’:
/var/lib/dkms/douane/0.8.2/build/douane.c:713:5: error: implicit declaration of function ‘task_lock’ [-Werror=implicit-function-declaration]
     task_lock(locked_task);
     ^
/var/lib/dkms/douane/0.8.2/build/douane.c:734:11: error: implicit declaration of function ‘task_unlock’ [-Werror=implicit-function-declaration]
           task_unlock(locked_task);
           ^
/var/lib/dkms/douane/0.8.2/build/douane.c:759:5: error: expected ‘while’ before ‘while_each_thread’
   } while_each_thread(task, locked_task);
     ^
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘find_task_from_socket_file’:
/var/lib/dkms/douane/0.8.2/build/douane.c:773:3: error: implicit declaration of function ‘for_each_process’ [-Werror=implicit-function-declaration]
   for_each_process(task)
   ^
/var/lib/dkms/douane/0.8.2/build/douane.c:774:3: error: expected ‘;’ before ‘{’ token
   {
   ^
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘initialize_module’:
/var/lib/dkms/douane/0.8.2/build/douane.c:1196:3: error: implicit declaration of function ‘nf_register_hook’ [-Werror=implicit-function-declaration]
   nf_register_hook(&nfho_outgoing);
   ^
/var/lib/dkms/douane/0.8.2/build/douane.c: In function ‘exit_module’:
/var/lib/dkms/douane/0.8.2/build/douane.c:1224:3: error: implicit declaration of function ‘nf_unregister_hook’ [-Werror=implicit-function-declaration]
   nf_unregister_hook(&nfho_outgoing);
   ^
cc1: some warnings being treated as errors
scripts/Makefile.build:315: recipe for target '/var/lib/dkms/douane/0.8.2/build/douane.o' failed
make[2]: *** [/var/lib/dkms/douane/0.8.2/build/douane.o] Error 1
Makefile:1550: recipe for target '_module_/var/lib/dkms/douane/0.8.2/build' failed
make[1]: *** [_module_/var/lib/dkms/douane/0.8.2/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.13.0-31-generic'
```

I am missing something, or is there a quickfix I can do?

Thanks!

**Comment by zedtux** [comment]
Thank you @teol for your issue. I think you're having the same issue as douane-dkms#26. Please followup on this other issue.
